language: python

sudo: false

python:
    - 3.5

before_install:
    - LILYPOND_SCRIPT=lilypond-2.19.59-1.linux-64.sh
    - LILYPOND_URL=http://download.linuxaudio.org/lilypond/binaries/linux-64
    - LILYPOND_URL=$LILYPOND_URL/$LILYPOND_SCRIPT
    - wget -q $LILYPOND_URL
    - sh $LILYPOND_SCRIPT --batch
    - git clone https://github.com/Abjad/abjad.git;
    - cd abjad; git checkout trevor/dev; pip install -e .[development]
    - echo `git branch`
    - cd ..
    - pip install --upgrade pip

install:
    - pip install coveralls
    - pip install coverage
    - pip install -r requirements.txt
    - pip install -e . 

script:
    - coverage run -a `which ajv` doctest ./baca
    # package contains only doctests!
    #- coverage run -a `which py.test` -rf ./baca

after_success:
    coveralls

notifications:
    email: false
