language: python

sudo: false

python:
    - 3.6

before_install:
    # upgrade pip:
    - pip install --upgrade pip
    # install lilypond:
    - LILYPOND_URL=http://download.linuxaudio.org/lilypond/binaries/linux-64
    - LILYPOND_SCRIPT=lilypond-2.19.80-1.linux-64.sh
    - wget -q $LILYPOND_URL/$LILYPOND_SCRIPT
    - sh $LILYPOND_SCRIPT --batch
    # clone abjad, checkout dev branch, install into site-packages:
    - git clone https://github.com/Abjad/abjad.git;
    - cd abjad; git checkout trevor/dev; pip install --quiet -e .; cd ..
    # clone rmakers, install into site-packages:
    - git clone https://github.com/Abjad/abjad-ext-rmakers.git
    - cd abjad-ext-rmakers; pip install -e .; cd ..
    # log directory status:
    - pwd
    - ls
    # install uqbar (for mypy):
    - pip install --target /tmp/typehints --no-deps uqbar>=0.2.11
    - ls /tmp/typehints
    # tell mypy where uqbar, abjad, rmakers are:
    - export MYPYPATH=$MYPYPATH:/tmp/typehints:./abjad:/.abjad-ext-rmakers
    #- export MYPYPATH=`pwd`/abjad:`pwd`/abjad-ext-rmakers:/tmp/typehints
    - echo $MYPYPATH
    # tell shell where doctest script is:
    - export PATH=$PATH:./baca/scr
    - echo $PATH
    - which doctest

install:
    - pip install coverage
    - pip install -r requirements.txt
    - pip install -e . 

script:
    - mypy baca
    - coverage run -a `which doctest` ./baca/*.py

after_success:
    - pip install coveralls
    - coveralls
