language: python

sudo: false

python:
    - 3.6

before_install:
    # install lilypond:
    - LILYPOND_URL=http://download.linuxaudio.org/lilypond/binaries/linux-64
    - LILYPOND_SCRIPT=lilypond-2.19.80-1.linux-64.sh
    - wget -q -O /tmp/$LILYPOND_SCRIPT $LILYPOND_URL/$LILYPOND_SCRIPT
    - sh /tmp/$LILYPOND_SCRIPT --batch

    # upgrade pip:
    - pip install --upgrade pip

    # clone & install abjad dev branch:
    - ABJAD=/tmp/abjad
    - git clone -b trevor/dev https://github.com/Abjad/abjad.git $ABJAD
    - pip install -e $ABJAD
    - export MYPYPATH=$ABJAD

    # clone & install rmakers:
    - RMAKERS=/tmp/abjad-ext-rmakers
    - git clone https://github.com/Abjad/abjad-ext-rmakers.git $RMAKERS
    - pip install -e $RMAKERS
    - export MYPYPATH=$MYPYPATH:$RMAKERS

    # install uqbar:
    - UQBAR=/tmp/uqbar
    - pip install --no-deps --target $UQBAR uqbar
    - export MYPYPATH=$MYPYPATH:$UQBAR

    # tell shell where doctest script is:
    - BACA_SCR=`pwd`/baca/scr
    - export PATH=$PATH:$BACA_SCR

    # log setup:
    - ls /tmp; pwd; ls; which doctest
    - echo $MYPYPATH
    - echo $PATH

install:
    - pip install coverage
    - pip install -r requirements.txt
    - pip install -e . 

script:
    - mypy baca
    - coverage run -a `which doctest` ./baca/*.py

after_success:
    - pip install coveralls
    - coveralls
