language: python

python:
    - 2.7
    - 3.4

sudo: false

before_install:
    - wget -q http://download.linuxaudio.org/lilypond/binaries/linux-64/lilypond-2.19.28-1.linux-64.sh
    - sh lilypond-2.19.28-1.linux-64.sh --batch
    - export PATH=/home/travis/bin:$PATH
    - pip install coveralls
    - pip install coverage

install:
    - pip install -r requirements.txt
    - pip install -e . 

script:
    - coverage run -a `which ajv` doctest ./baca
    - coverage run -a `which py.test` -rf ./baca

after_success:
    coveralls

notifications:
    email: false