language: python

python:
    - 3.5

sudo: false

before_install:
    - export PATH=/home/travis/bin:$PATH
    - wget -q http://download.linuxaudio.org/lilypond/binaries/linux-64/lilypond-2.19.50-1.linux-64.sh
    - sh lilypond-2.19.50-1.linux-64.sh --batch
    - git clone https://github.com/Abjad/abjad.git; cd abjad; git checkout trevor/dev; pip install -e .[development]
    - echo `git branch`
    - cd ..
    - pip install --upgrade pip

install:
    - pip install coveralls
    - pip install coverage
    - pip install -r requirements.txt
    - pip install -e . 

script:
    - coverage run -a `which ajv` doctest ./baca
    - coverage run -a `which py.test` -rf ./baca

after_success:
    coveralls

notifications:
    email: false
