language: python

sudo: false

python:
    - 3.6

before_install:
    # upgrade pip:
    - pip install --upgrade pip

    # install lilypond:
    - LILYPOND_URL=http://download.linuxaudio.org/lilypond/binaries/linux-64
    - LILYPOND_SCRIPT=lilypond-2.19.80-1.linux-64.sh
    - wget -q $LILYPOND_URL/$LILYPOND_SCRIPT
    - sh $LILYPOND_SCRIPT --batch

    # clone & install abjad dev branch:
    - ABJAD=/tmp/abjad
    - git clone -b trevor/dev https://github.com/Abjad/abjad.git $ABJAD
    - pip install -e $ABJAD

    # clone & install rmakers:
    - RMAKERS=/tmp/abjad-ext-rmakers
    - git clone https://github.com/Abjad/abjad-ext-rmakers.git $RMAKERS
    - pip install -e $RMAKERS

    # install uqbar:
    - UQBAR=/tmp/typehints
    #- pip install --target /tmp/typehints --no-deps uqbar>=0.2.11
    - pip install --no-deps --target $UQBAR uqbar>=0.2.11

    - ls /tmp
    - ls /tmp/typehints

    # tell mypy where uqbar, abjad, rmakers are:
    - export MYPYPATH=$UQBAR:$ABJAD:$RMAKERS
    - echo $MYPYPATH
    # tell shell where doctest script is:
    - export PATH=$PATH:./baca/scr
    - echo $PATH
    - which doctest
    # log directory status:
    - pwd
    - ls

install:
    - pip install coverage
    - pip install -r requirements.txt
    - pip install -e . 

script:
    - mypy baca
    - coverage run -a `which doctest` ./baca/*.py

after_success:
    - pip install coveralls
    - coveralls
