language: python

sudo: false

python:
    - 3.6

before_install:
    - LILYPOND_SCRIPT=lilypond-2.19.80-1.linux-64.sh
    - LILYPOND_URL=http://download.linuxaudio.org/lilypond/binaries/linux-64
    - LILYPOND_URL=$LILYPOND_URL/$LILYPOND_SCRIPT
    - wget -q $LILYPOND_URL
    - sh $LILYPOND_SCRIPT --batch
    - git clone https://github.com/Abjad/abjad.git;
    - cd abjad; git checkout trevor/dev; pip install -e .[development]
    - echo `git branch`
    - cd ..
    - pip install --upgrade pip
    - MYPYPATH=`pwd`:`pwd`/abjad
    - export MYPYPATH
    - echo $MYPYPATH

install:
    - pip install coverage
    - pip install -r requirements.txt
    - pip install -e . 

script:
    - mypy baca
    - coverage run -a `which ajv` doctest --external-modules=baca ./baca

after_success:
    - pip install coveralls
    - coveralls

notifications:
    email: false
